### PR TITLE
Civix upgrade

### LINKED ISSUE #4: Deprecation warning in PHP 7.4
I'm getting the following error:

```
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in org.civicoop.membershippayment/membershippayment.civix.php on line 155
```

Regenerating the `civix` file should fix this.

### PR DESCRIPTION
**Pull request by wmortada**
Fixes #4.

Update to make extension compatible with latest versions of CiviCRM and PHP.

### CODE REVIEW

**Comment by wmortada** [comment]
@AlainBenbassat or @jaapjansma thanks for creating this extension. We have it working successfully on at least one site but it needs a civix upgrade. Are you able to merge this PR and release a new version so that others can use it too? Thanks!

**Comment by jaapjansma** [comment]
Thanks @wmortada

**Comment by jaapjansma** [comment]
I have released a new version.

**Comment by wmortada** [comment]
Thanks @jaapjansma

**Pull request merged**
